package com.bestvike.linq.exception;

/**
 * Created by 许崇雷 on 2019-04-23.
 */
public enum ExceptionArgument {
    collectionSelector,
    count,
    elementSelector,
    enumerable,
    first,
    func,
    index,
    inner,
    innerKeySelector,
    keySelector,
    outer,
    outerKeySelector,
    predicate,
    resultSelector,
    second,
    selector,
    source,
    //extension
    action,
    array,
    clazz,
    collator,
    collection,
    comparison,
    condition,
    current,
    elements,
    formatter,
    hasNext,
    iterable,
    locale,
    match,
    moveNext,
    newSize,
    next,
    obj,
    options,
    other,
    startIndex,
}
