# Workflow file of GitHub Actions

name: build

on:
  push:
    branches:
      - master
      - feature/*
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ 8, 11, 16, 17 ]

    steps:
      - name: Checkout scm
        uses: actions/checkout@v3

      - name: Set up jdk
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}

      - name: Build with Maven
        run: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

      - name: Test with Maven
        run: mvn test -B

      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          name: Codecov on jdk ${{ matrix.java }}
          fail_ci_if_error: false
